In [1]:
num = [1, 2,3, 4, 5, 6, 7, 8, 9, 10]
for i in num:
    print(i)


1
2
3
4
5
6
7
8
9
10


In [2]:
statement = "I am happy with the product"
print("happy" not in statement)

False


In [3]:
statement = "I am happy with the product"
print("happy"  in statement)

True


In [4]:
name = "Anshu Subedi"
print(name[2:8])

shu Su


In [5]:
name = "Anshu Subedi"
print(name[2:])

shu Subedi


In [6]:
name = "vipin Parajuli"
print(name.upper())

VIPIN PARAJULI


In [7]:
name = " Vipin Parajuli"
print(name.strip())
name = name.strip()

Vipin Parajuli


In [8]:
import numpy as np
lists = [1,2,3,5,6,"Dev",3.0]
lists

[1, 2, 3, 5, 6, 'Dev', 3.0]

In [9]:
nparray = np.array([1,2,3,4,5,6,"Dev", 4,5,12,123])
nparray


array(['1', '2', '3', '4', '5', '6', 'Dev', '4', '5', '12', '123'],
      dtype='<U11')

In [10]:
nparray[0]

'1'

In [11]:
nparray[7]

'4'

In [12]:
nparray[:6]

array(['1', '2', '3', '4', '5', '6'], dtype='<U11')

In [13]:
nparray[0] = 30
nparray

array(['30', '2', '3', '4', '5', '6', 'Dev', '4', '5', '12', '123'],
      dtype='<U11')

In [14]:
nparray = np.array([1,2,3,4,5,6,7,8,9])
type(nparray)

numpy.ndarray

###### list VS numpyarray

In [16]:
l = [1,2,3,4,5,6,7,8]
ndarray = np.array([1,2,3,4,5,6,7,8])
ndarray

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
type(ndarray)

numpy.ndarray

In [18]:
ndarray.ndim

1

In [19]:
ndarray.shape

(8,)

In [20]:
ndarray.size

8

In [21]:
ndarray.dtype

dtype('int32')

In [54]:
lists = [1,2,3,4,5]

In [56]:
######1-D Vs 2-D lists

In [49]:
lists = [1,2,3,4,5]

In [51]:
import numpy as np
lists = [1,2,3,4,5]
lists

[1, 2, 3, 4, 5]

In [53]:
###2-D numpy array

In [55]:
ndarray2 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
ndarray2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
ndarray2.ndim

2

In [59]:
ndarray2.size

15

In [61]:
ndarray2.shape

(3, 5)

In [63]:
ndarray2.dtype

dtype('int32')

In [65]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.empty(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [73]:
np.linspace(0,20, num=6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [77]:
ndarray3 = np.array([34,56,43,23,45,87,89])
ndarray3

array([34, 56, 43, 23, 45, 87, 89])

In [79]:
np.sort(ndarray3)

array([23, 34, 43, 45, 56, 87, 89])

In [87]:
nd1 = np.array([[1,2,31], [3,4,5]])
nd2 = np.array([[6,7,21], [8,9,10]])
nd2

array([[ 6,  7, 21],
       [ 8,  9, 10]])

In [89]:
np.concatenate((nd1,nd2), axis = 0)

array([[ 1,  2, 31],
       [ 3,  4,  5],
       [ 6,  7, 21],
       [ 8,  9, 10]])

In [91]:
np.concatenate((nd1,nd2), axis = 1)

array([[ 1,  2, 31,  6,  7, 21],
       [ 3,  4,  5,  8,  9, 10]])

In [ ]:
nd1 = np.array([1,2,31,3,4,5])

In [95]:
nd1

array([[ 1,  2, 31],
       [ 3,  4,  5]])

In [97]:
nd1 = np.array([1,2,31,3,4,5])
nd1

array([ 1,  2, 31,  3,  4,  5])

In [99]:
nd1.reshape(3,2)

array([[ 1,  2],
       [31,  3],
       [ 4,  5]])

In [101]:
nd1.reshape(6,1)

array([[ 1],
       [ 2],
       [31],
       [ 3],
       [ 4],
       [ 5]])

In [105]:
nd1 = np.array([1,2,31,3,4,5])
nd1[:]

array([ 1,  2, 31,  3,  4,  5])

In [107]:
nd1[:3]

array([ 1,  2, 31])

In [109]:
nd1[3:]

array([3, 4, 5])

In [111]:
nd1[-2:]

array([4, 5])

In [113]:
[nd1<8]

[array([ True,  True, False,  True,  True,  True])]

In [115]:
nd2 = np.array([0,1,2,31,3,4,5])
nd2


array([ 0,  1,  2, 31,  3,  4,  5])

In [117]:
nd2.nonzero()

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

In [119]:
nd3 = np.array([0,1,2,3,54])
nd3

array([ 0,  1,  2,  3, 54])

In [123]:
nd3 =nd3 * 2
nd3

array([  0,   4,   8,  12, 216])

In [125]:
nd3.min()

0

In [127]:
nd3.max()

216

In [129]:
nd3.sum()

240